#ifndef RUNTIMEEQUATION_GLOBAL_H
#define RUNTIMEEQUATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RUNTIMEEQUATION_LIBRARY)
#  define RUNTIMEEQUATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RUNTIMEEQUATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RUNTIMEEQUATION_GLOBAL_H
